/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Confirm': '确认',
    'Event Log': '事件日志',
    'Download as file': '下载存档文件',
    'Coins': '币',
    'Coin Icon': '币图标',
    'Thank you.': '感谢。',
    'SUCCESS': '成就',
    'STATS': '统计',
    'Start': '开始',
    'SETTINGS': '设置',
    'SHOP': '商店',
    'RESEARCH': '研究',
    'Machines owned': '拥有的机器',
    'Make a Backup': '进行备份',
    'Market Image': '市场图像',
    'Market Media': '市场媒体',
    'Prestige': '声望',
    'Please export before you restart.': '在重新启动之前，请导出。',
    'Prestige Mode': '声望模式',
    'Restart Game': '重新游戏',
    'Reset NOW': '现在重置',
    'Reset Game': '重置游戏',
    'YOUR MINING RIG': '您的采矿设备',
    'You crazy': '你疯了',
    'TRON': '波场',
    'NSA Datacenter': 'NSA数据中心',
    'Online Shop': '线上商店',
    'Parents Bedroom': '父母卧室',
    'Planet Image': '行星图像',
    'FAQ': '问答',
    'CHANGELOG': '更新日志',
    'CONTACT': '联系方式',
    'Total Money Spent (this game': '总计花掉的钱（本轮游戏',
    'Total Money Made (this game': '总计赚到的钱（本轮游戏',
    'Total Money Made (before reset': '总计赚到的钱（上次重置',
    'Upgrades from shop are permanent.': '从商店升级是永久性的。',
    'Upgrades researched': '已研究升级',
    'Loading': '加载',
    "Get 20,000 dollars. Good for resets": "获得20,000美元。适合重置",
    "Get 500 dollars. Good for resets": "得到500美元。适合重置",
    "Get 600,000 dollars. Good for resets": "获得 600,000 美元。适合重置",
    "Get a free ATI Mach 64. Good for resets": "获得免费的 ATI Mach 64。适合重置",
    "Get additional 15% of your BTC/s rate while being offline": "离线时获得额外 15% 的 BTC/s 费率",
    "Get additional 25% of your BTC/s rate while being offline": "离线时获得额外 25% 的 BTC/s 费率",
    "Get additional 50% of your BTC/s rate while being offline": "离线时获得额外 50% 的 BTC/s 费率",
    "Get coins and levels through prestige mode. For further help see FAQs.": "通过声望模式获得金币和等级。如需进一步帮助，请参阅常见问题解答。",
    "Gold Digger": "淘金者",
    "Good Mining Bonus": "良好的采矿奖金",
    "Good Money Bag": "好钱袋",
    "Good Research Bonus": "良好的研究奖金",
    "Hack Attacks": "黑客攻击",
    "Hacking Expert": "黑客专家",
    "Hacking Level: Asian": "黑客级别：亚洲",
    "Hardware pics": "硬件图片",
    "here": "这里",
    "Hier wurde der kleine Bitcoiner am 19. Juni 2014 geboren": "Hier wurde der kleine Bitcoiner am 19. Juni 2014 geboren",
    "Highscore will be reseted with prestige level up.": "高分将随着声望等级的提高而重置。",
    "Hilarious": "搞笑",
    "Hint: English is not my first language.": "提示：英语不是我的第一语言。",
    "Hint: If you want to open this amazing fireworks effect again,": "提示：如果你想再次打开这个惊人的烟花效果，",
    "Hint: You could also ask in chat.": "提示：您也可以在聊天中提问。",
    "Holy Grail": "圣杯",
    "Hustler Multi": "骗子乘数",
    "I have currently no time for developing, I'm really sorry. Thanks for playing.": "我目前没有时间进行开发，我真的很抱歉。感谢参与。",
    "I think you can stop now": "我想你现在可以停下来了",
    "IBM Roadrunner '08": "IBM Roadrunner '08",
    "If you bought the \"Coincidence?\" upgrade in shop, the chance is 1/60 every 3 seconds.": "如果您在商店购买了“巧合？”升级，几率为每 3 秒 1/60。",
    "if you can't get abstinence achievement.": "如果你不能获得禁欲成就。",
    "If you have feedback for me, write an email or use the feedback option.": "如果您对我有反馈，请写一封电子邮件或使用反馈选项。",
    "If you still want to remove them, use an Adblocker. I don't bother you.": "如果您仍想删除它们，请使用 Adblocker。我不打扰你。",
    "If you want to get mentioned for donating, leave a hint.": "如果您想因捐赠而被提及，请留下提示。",
    "If you want to, do so! (Even though it's boring": "如果你愿意，那就去做吧！ （虽然很无聊",
    "If you want to, do so! (Even though it's boring)": "如果你愿意，那就去做吧！ （虽然很无聊）",
    "If your browser doesn't support Javascript, get one like Google Chrome or Firefox.": "如果您的浏览器不支持 Javascript，请使用 Google Chrome 或 Firefox 之类的浏览器。",
    "Imperator": "皇帝",
    "import": "导入",
    "Impressum/ Legal Notice": "印象/法律声明",
    "Impressum/Legal Notice": "印象/法律声明",
    "Improve your besttimes by using prestige system": "通过使用声望系统改善您的最佳时间",
    "Improvments for your virtual life.": "改善您的虚拟生活。",
    "in": "在",
    "Increase your BTC/s by 1%": "将您的 BTC/s 提高 1%",
    "Increase your BTC/s by 10%": "将您的 BTC/s 提高 10%",
    "Increase your BTC/s by 100%": "将您的 BTC/s 提高 100%",
    "Increase your BTC/s by 1000%": "将您的 BTC/s 提高 1000%",
    "infinite in stock": "无限库存",
    "Inflation": "通货膨胀",
    "instead of (TimeThisSessionPassed / 10000) * BTC": "而不是 (此会话经过的时间 / 10000) * BTC",
    "into the command line!": "进入命令行！",
    "Is this even legal?": "这甚至合法吗？",
    "Jupiter": "木星",
    "Just email me": "给我发电子邮件",
    "Just the beginning": "只是开始",
    "Just the beginning v2": "刚刚开始 v2",
    "just type": "只需键入",
    "Keep the game alive: a dollar a day keeps the the doctor (not THE doctor) away.": "保持游戏活力：一天一美元让医生（而不是医生）远离。",
    "Kim Dotcom '74": "金网络'74",
    "Kim Dotcom Graphic": "金网络图形",
    "kitty": "猫咪",
    "Kitty": "猫咪",
    "Lazy Selling": "懒惰销售",
    "Legacy": "遗产",
    "Load Backup": "负载备份",
    "Locked Icon": "未解锁图标",
    "Mach Speed": "马赫速度",
    "Market 2 Image": "市场 2 图片",
    "mega.co.nz": "巨型网站",
    "Meh": "咩",
    "Micro Mining Bonus": "很少的挖矿奖励",
    "Mini Mining Bonus": "略少的挖矿奖励",
    "Mini Money Bag": "迷你钱包",
    "Money ": "钱",
    "Money Image": "金钱形象",
    "Money Per Click = $1 + (ResearchFactor[5|10|..]) * 0.8 * (Bitcoins/s + 0.7 * NumberOfZuseZ3Owned * Bitcoins": "每次点击费用 = 1 美元 + (研究因子[5|10|..]) * 0.8 * (比特币/秒 + 0.7 * 拥有ZuseZ3的数量 * 比特币",
    "more reset-coins for prestige level": "更多声望级别的重置硬币",
    "Multiply hacking money by ten (you need one research at least": "将黑客资金乘以十（您至少需要一项研究",
    "New era": "新时代",
    "Nice power bill": "不错的电费单",
    "Night Gaming": "夜间游戏",
    "Night Owl": "夜猫子",
    "Night Owl Sr.": "夜猫子高级",
    "Nightly Build": "每晚构建",
    "no prestige level! (You need": "没有声望级别！ （你需要",
    "No risk": "没有风险",
    "Normal Size": "正常尺寸",
    "Note: For your very first coin you need ~1 quadrillion dollars.": "注意：对于您的第一枚比特币，您需要约 1 quadrillion 美元。",
    "Note: It is possible to gain coins through game events, not only by prestige mode.": "注意：不仅通过声望模式，还可以通过游戏活动获得金币。",
    "": "",
    "Note: I stopped developing this game. I have not much time for developing this good but bad programmed, already well advanced game. Maybe there will be a sequel (don't expect anything).\n                        I thank you for playing bitcoinergame! My email address is still up and will be, so feel free to write me an email.": "注:我不再开发这款游戏。我没有太多的时间来开发这个好的但坏的编程，已经很先进的游戏。也许会有续集(不要抱任何期望)。我感谢你玩比特币矿工放置!我的电子邮件地址仍然是，并将是，所以请随时给我写电子邮件。",
    "Time Wisely Used (this game": "明智地使用时间（这个游戏",
    "To the stars": "给星星",
    "todo list": "待办事项清单",
    "Townhall": "市政厅",
    "TRON Highscore": "波场 高分",
    "TRON Rounds Played": "波场 回合数",
    "Unlock a kitty as background. Activate with": "解锁一只小猫作为背景。激活",
    "unlocking achievements": "解锁成就",
    "up to date": "最新",
    "USB ASIC Miner x10 '12": "USB ASIC 矿工 x10 '12",
    "USD/BTC ": "美元/比特币",
    "Use WASD/arrow keys to move, any other key to pause, Enter to restart": "使用 WASD/箭头键移动，任何其他键暂停，Enter 重新启动",
    "Using 2D-graphics for mining. Why not?": "使用 2D 图形进行挖掘。为什么不？",
    "Want to donate": "想捐款",
    "Well, that escalated quickly": "嗯，升级很快",
    "Why not ten?": "为什么不是十个？",
    "WolframALPHA Formula": "WolframALPHA 公式",
    "www.bitcoinergame.com": "www.bitcoinergame.com",
    "x base Multi": "x 基础多",
    "x BTC/s": "x 比特币/秒",
    "You can later load your backup even if you resetted main savegame. Just for lazy people, export manually everytime.": "即使您重置了主存档游戏，您也可以稍后加载备份。只为懒人，每次手动导出。",
    "You obtained every single achievement! Your work is done here (You also got 100 Coins).": "你获得了每一个成就！您的工作在这里完成（您还获得了 100 个硬币）。",
    "Your health is your current amount of BTC/10.": "您的健康是您当前的 BTC/10 数量。",
    "Your room": "你的房间",
    "game saved": "游戏已保存",
    "Gameception": "游戏感受",
    "General feedback, questions and comments?": "一般反馈、问题和意见？",
    "Get 10% of your BTC/s rate while being offline": "离线时获得 10% 的 BTC/s 费率",
    "Get 100,000 dollars. Good for resets": "获得 100,000 美元。适合重置",
    "Get 2 coins for every new research": "每项新研究获得 2 个硬币",
    "Git游戏": "Git游戏",
    "machines are calculating 0.0001 Bitcoins per second": "机器每秒计算 0.0001 个比特币",
    "Next machine costs": "下一台机器成本",
    "Note: Keep in mind that it is harder to get coins on a higher prestige level.": "注意：请记住，获得更高声望级别的硬币更难。",
    "Note: Thanks for your feedback, maybe you will find your own stuff here. Keep checking changelog.": "注意：感谢您的反馈，也许您会在这里找到自己的东西。继续检查变更日志。",
    "Older changes": "较早的更改",
    "on your keyboard. Or click": "在你的键盘上。或点击",
    "One Mille": "一英里",
    "Online Shopping": "网上购物",
    "Onlineshop Image": "网店形象",
    "own subreddit": "自己的子版块",
    "Patience": "耐心",
    "Phone House": "电话屋",
    "Phone Image": "手机图片",
    "Place for 1000 machines": "可容纳 1000 台机器",
    "Place for 15 machines": "15台机器的地方",
    "Place for 200 machines": "可容纳 200 台机器",
    "Play without ads on kongregate": "在kongregate上玩无广告",
    "playing TRON": "玩波场",
    "Please report bugs, feedback or hints as usual via chat or mail at": "请像往常一样通过聊天或邮件报告错误、反馈或提示",
    "Points so far": "到目前为止的积分",
    "prestige mode.": "声望模式。",
    "Prestige Shop": "声望店",
    "Prevent BTC/USD exchange rate from falling too deep!": "防止BTC/USD汇率跌得太深！",
    "Purchased": "已购买",
    "Q: Do I lose earned coins when I'm going to restart?": "问：当我要重新开始时，我会失去赚到的硬币吗？",
    "Q: How can I support the game?": "问：如何支持游戏？",
    "Q: How do I get a Prestige Level?": "问：如何获得声望等级？",
    "Q: How do I get awards?": "问：我如何获得奖励？",
    "Q: How do I get money?": "问：我如何获得金钱？",
    "Q: How do I open the command line?": "问：如何打开命令行？",
    "Q: How do I unlock the adventure/dungeon/whatever mode?": "问：我如何解锁冒险/地牢/其他模式？",
    "Q: How do I use the classic design? I hate this shi**y background OR How do i use the kitty background?": "问：如何使用经典设计？我讨厌这个 shi**y 背景或者我如何使用小猫背景？",
    "Q: How does the prestige system work?": "问：声望系统如何运作？",
    "Q: How high is the chance that a random event appears?": "Q：随机事件出现的几率有多大？",
    "Q: How is the BTC/s boost determined?": "问：BTC/s 的提升是如何确定的？",
    "Q: I can't buy anything in shop! I don't understand it.": "问：我在商店买不到任何东西！我不明白。",
    "Q: I don't understand the hacking system.": "问：我不了解黑客系统。",
    "Q: I have already coins, but I'm Prestige 0. Why?": "Q：我已经有金币了，但是我是Prestige 0，为什么？",
    "Q: Is cheating allowed?": "问：是否允许作弊？",
    "Q: Only errors. Fix the game!": "问：只有错误。修复游戏！",
    "Q: Remove the annoying ads!": "问：去除烦人的广告！",
    "Q: Well, how do I get Bitcoins?": "问：嗯，我如何获得比特币？",
    "Q: What are bad points?": "问：什么是坏点？",
    "Q: What are researches?": "问：什么是研究？",
    "Q: What does \"USD/BTC\" mean?": "问：“USD/BTC”是什么意思？",
    "Q: Where do I see the cost per bitcoins/s?": "问：我在哪里可以看到每比特币/秒的成本？",
    "Random Events": "随机事件",
    "randomEvent();": "随机事件（）；",
    "Randoms have a 25% higher chance to show": "随机出现的机会增加 25%",
    "Randoms stay twice as long": "随机数的停留时间是原来的两倍",
    "real": "真实的",
    "Real Hustling": "真正的喧嚣",
    "Reduced Costs": "降低成本",
    "Research Center": "研究中心",
    "Research Center 1": "研究中心1",
    "Reset? Going further? It's up to you now.": "重启？走得更远？现在由你决定。",
    "Restart": "重新开始",
    "Richie Rich": "里奇里奇",
    "root@secretDevice:~$": "root@secretDevice:~$",
    "Ruby Icon": "红宝石图标",
    "Sandor Clegane": "桑铎克里冈",
    "save game": "保存游戏",
    "SELL 1": "卖出 1",
    "sell 10": "卖出 10",
    "SELL 10": "卖出 10",
    "sell all": "全部卖出",
    "Sell Percentage": "卖出百分比",
    "Settings and Options": "设置和选项",
    "show upgrades researched": "显示升级研究",
    "Small Money Bag": "小钱袋",
    "Small Research Bonus": "小额研究奖金",
    "Sources": "来源",
    "Spare your finger": "放开你的手指",
    "Stagnation is regression": "停滞就是倒退",
    "Start Prestige Mode": "开始声望模式",
    "Starting": "开始",
    "Startscreen is black! It's a feature (not a bug": "开始屏幕是黑色的！这是一个功能（不是错误",
    "Startscreen is black! It's a feature (not a bug)": "开始屏幕是黑色的！这是一个功能（不是错误）",
    "Status: Nerd": "状态：书呆子",
    "Status: Online": "状态：在线",
    "Status: Reallife": "状态：现实生活",
    "Status: Sheldon": "状态：谢尔顿",
    "Stop": "停止",
    "Stop wasting your time": "别再浪费你的时间了",
    "Switch big number formating": "切换大数格式",
    "Terminals ain't only for airplanes": "航站楼不仅适用于飞机",
    "Thank you for playing Bitcoiner!": "感谢您玩比特币矿工放置！",
    "Thanks to all player, reddit for making the game \"famous\". Especially to all people who are giving feedback via mail, feedback function or chat. It's also your game.": "感谢所有玩家，reddit 让游戏“出名”。特别是所有通过邮件、反馈功能或聊天提供反馈的人。这也是你的游戏。",
    "Thanks!": "谢谢！",
    "That wouldn't be possible!": "那是不可能的！",
    "The new hightech 4-bit CPU. White ceramic plates and golden cap for free!": "新的高科技 4 位 CPU。免费的白色陶瓷盘子和金色帽子！",
    "A: You have to buy your first mining machine, like the ZUSE Z3. Every machine has his own BTC per second rate, e.g. 0.5 BTC/s.\n                        You can sell BTC to get more money. (Auto-sell has a 1% fee and doesn't use upgrades)": "A：你必须购买你的第一台矿机，比如 ZUSE Z3。 每台机器都有自己的 BTC 每秒速率，例如 0.5 BTC/s。\n你可以卖掉 BTC 来获得更多的钱。 （自动卖出收取 1% 的费用且不使用升级）",
    "for 1 BTC": "1 比特币",
    "Gameception [locked]  [+10": "游戏体验 [未解锁] [+10",
    "Hack your first dollar": "破解你的第一美元",
    "Have every gold award": "拥有每一个金奖",
    "Hilarious [locked]  [+50": "搞笑[未解锁] [+50",
    "Imperator [locked]  [+2": "元首 [未解锁] [+2",
    "Is this even legal? [unlocked]  [1": "这甚至合法吗？ [已解锁] [1",
    "Make 1 million dollar in less than 15 minutes (in wallet) (prestige allowed": "在 15 分钟内赚到 100 万美元（在钱包里）（允许声望",
    "New era [unlocked]  [1": "新时代[已解锁] [1",
    "Nice power bill [locked]  [+5": "不错的电费单[未解锁] [+5",
    "obtained]": "获得]",
    "Online Shopping [locked]  [+5": "网购[未解锁] [+5",
    "Patience [locked]  [+30": "耐心 [未解锁] [+30",
    "Play 100 rounds of TRON": "玩 100 轮 TRON",
    "Reach Level 10 in Online Shop": "在网上商店达到 10 级",
    "reached after 32s": "32 秒后到达",
    "reached after 54s": "54s 后到达",
    "Research 45 Upgrades": "研究 45 升级",
    "Richie Rich [locked]  [+2": "Richie Rich [未解锁] [+2",
    "Sandor Clegane [locked]  [+10": "桑铎·克里冈 [未解锁] [+10",
    "Save up 1 billion $": "节省 10 亿美元",
    "Save up 1 octillion  dollars": "节省 1 octillion 美元",
    "Sell BTCs when BTC rate is more than 606$ (Won't work with auto-sell": "当 BTC 价格超过 606 美元时卖出 BTC（不适用于自动卖出",
    "Stagnation is regression [locked]  [+10": "停滞是回归[未解锁] [+10",
    "Status: Nerd [locked]  [+5": "状态：书呆子[未解锁] [+5",
    "Stop wasting your time [locked]  [+2": "别再浪费你的时间了[未解锁][+2",
    "The score is depending on your distance you reached. (Pixels/100": "分数取决于您到达的距离。 （像素/100",
    "There's a place..": "有地方..",
    "There's a place.. [locked]  [+100": "有个地方..[未解锁] [+100",
    "This feature is BETA Status, use at your own risk (Don't forget to export": "此功能为 BETA 状态，使用风险自负（不要忘记导出",
    "This is a Javascript based game. Please allow Javascript in your browser.": "这是一个基于 Javascript 的游戏。请允许在您的浏览器中使用 Javascript。",
    "THIS IS NOT PRESTIGE": "这不是声望",
    "Tian-He '13": "天河'13",
    "Time Wisely Used (all time": "明智地使用时间（所有时间",
    "A: No, there is no way to lose coins.": "A：不，没有办法丢失硬币。",
    "A: No. BTC/s Multi and so on are forever, you will only lose money bags and the ATI Mach.": "A: 不会。BTC/s Multi 等是永远的，你只会输钱袋和 ATI 马赫。",
    "A: No. BTC/s Multi and so on are forever, you will only lose money bags and the ATI Mach. ": "A: 不会。BTC/s Multi 等是永远的，你只会输钱袋和 ATI 马赫。",
    "A: Once you researched \"Asynchronous Functions\", the chance to show is 1/80 every 3 seconds.": "A：一旦你研究了“异步函数”，展示的机会是每3秒1/80。",
    "A: Open the command line, then type": "A：打开命令行，然后输入",
    "A: Sure it is. Bitcoiner is a clientbased game, so you can change all variables, savegames and so on.": "答：当然可以。 Bitcoiner 是一款基于客户端的游戏，因此您可以更改所有变量、保存游戏等。",
    "A: Tell your friends about it. That's it!": "A：告诉你的朋友。就是这样！",
    "A: The basic hacking money is $1. After researching the \"botnet\" upgrades, you'll gain more money through hacking. Take a look on the formula": "A: 基本的黑客资金是 1 美元。在研究了“僵尸网络”升级之后，你会通过黑客获得更多的钱。看一下公式",
    "A: The shop is a good place to buy comprehensive upgrades. You need coins to pay.": "- 答：商店是购买全面升级的好地方。你需要硬币来支付。",
    "A: This game is clientbased, you every player could change his money and so on. This would be a who-is-the-best-cheater highscore list.": "A：这个游戏是基于客户端的，你每个玩家都可以换钱等等。这将是一个谁是最好的骗子高分名单。",
    "A: You can also gain some coins through achievements, playing TRON and Random Events.": "A：您还可以通过成就、玩波场和随机事件获得一些金币。",
    "A: You have to buy your first mining machine, like the ZUSE Z3. Every machine has his own BTC per second rate, e.g. 0.5 BTC/s.\n                        You can sell BTC to get more money. (Auto-sell has a 1% fee and doesn't use upgrades": "A：你必须购买你的第一台矿机，比如 ZUSE Z3。每台机器都有自己的 BTC 每秒速率，例如0.5 BTC/s。\n你可以卖掉 BTC 来获得更多的钱。 （自动卖出收取 1% 的费用且不使用升级",
    "A: You have to check the checkbox in Settings tab.": "答：您必须选中“设置”选项卡中的复选框。",
    "Abstinence": "节制",
    "Abstinence [locked]  [+30": "禁欲 [未解锁] [+30",
    "Activate your bought kitty background with": "激活您购买的小猫背景",
    "Addicted to you-, mining": "沉迷于你——挖矿",
    "Addicted to you-, mining [locked]  [+10": "沉迷于你-，采矿[未解锁] [+10",
    "admin@wernersbacher.de": "admin@wernersbacher.de",
    "Advanced": "先进的",
    "ADVENTURE": "冒险",
    "Advertising": "广告",
    "After next restart you need 150 coins for a prestige level up, then 225, and so on.": "下次重新启动后，您需要 150 个硬币来提升声望等级，然后是 225 个，依此类推。",
    "AMD Athlon K7 '99": "AMD 速龙 K7 '99",
    "AMD Athlon K7 Graphic": "AMD 速龙 K7 显卡",
    "AMD Bulldozer '11": "AMD 推土机 '11",
    "AMD Radeon HD 7990 '12": "AMD Radeon HD 7990 '12",
    "and": "和",
    "and confirm with your enter key. (Get other one back with": "并用您的回车键确认。 （取回另一个",
    "Annoying seller": "烦人的卖家",
    "Are you afk?": "你是afk吗？",
    "Arrow Icon": "箭头图标",
    "ATI Mach 64 '91": "ATI 马赫 64 '91",
    "ATI Mach 64 Graphic": "ATI Mach 64 显卡",
    "auto-sell": "自动卖出",
    "Autoselling will use manual selling bonus": "自动卖出将使用手动销售奖金",
    "B-CLASS PHOTOS": "",
    "Background Image": "背景图片",
    "Backhander": "反手",
    "bad points": "坏点",
    "basement": "地下室",
    "Be online for 1 day": "上线1天",
    "Beat 30 Bosses": "击败 30 个 Boss",
    "beta tron game": "Beta tron 游戏",
    "Better graphics and animations will come! (Really, someday..": "更好的图形和动画将会出现！ （真的，总有一天……",
    "Better graphics and animations will come! (Really, someday..)": "更好的图形和动画将会出现！ （真的，总有一天……）",
    "Big Mining Bonus": "大挖矿红利",
    "Big Money Bag": "大钱袋",
    "Big Research Bonus": "大研究奖金",
    "bitcoiner.wernersbacher.de": "bitcoiner.wernersbacher.de",
    "bitcoinergame.com": "比特币矿工放置",
    "bitcoinergame.com 0.7c1": "比特币矿工放置 0.7c1",
    "bitcoins?": "比特币？",
    "bling bling": "亮闪闪",
    "bling bling [locked]  [+10": "bling bling [未解锁] [+10",
    "Bonus Multi": "奖金多",
    "BTC": "比特币",
    "BTC\n                            |": "比特币\n |",
    "BTC ": "比特币",
    "BTC: 1EWRVm1X441D9x8nL4xc7aAewrvTKETCCe": "比特币：1EWRVm1X441D9x8nL4xc7aAewrvTKETCCe",
    "BTC/s": "比特币/秒",
    "BTC/s ": "比特币/秒",
    "BTC/s Boost Icon": "BTC/s 提升图标",
    "BTC/s Multi": "BTC/s 多",
    "BUY 10": "买 10",
    "Buy 10,000 machines": "购买 10,000 台机器",
    "Buy 2000 machines": "购买2000台机器",
    "Buy 500 machines": "购买500台机器",
    "Buy a brandnew ZUSE Z3": "购买全新的 ZUSE Z3",
    "Cancel": "取消",
    "Canvas is not supported in your browser.": "您的浏览器不支持画布。",
    "Central Market": "中央市场",
    "Changelog": "变更日志",
    "check out our": "看看我们的",
    "cidence?": "信心？",
    "classic.false": "经典的.false",
    "classic.true": "经典的.true",
    "Click 299 random events": "点击 299 个随机事件",
    "Clickbot": "点击机器人",
    "Clickception": "点击接收",
    "Clicking Power": "点击电源",
    "cmd": "命令",
    "code based on TRON 219 Bytes": "基于 TRON 219 字节的代码",
    "Coin": "硬币",
    "Coincidence? I think not": "巧合？我想不是",
    "Coincidence? I think not [locked]  [+30": "巧合？我认为不是[未解锁] [+30",
    "CONGRATULATIONS": "恭喜",
    "Contact": "接触",
    "cool Paint skills": "炫酷的绘画技巧",
    "Danke an alle Beta-Tester, free-way.me, ngb.to, RBF Clan, komische def-net Leute, andere die sowieso keiner von euch kennt sowie zuk�nftiger Spieler.": "Danke an alle Beta-Tester, free-way.me, ngb.to, RBF Clan, komische def-net Leute, andere die sowieso keiner von euch kennt sowie zuk�nftiger Spieler。",
    "Danke an..": "丹科安..",
    "Datacentre Image": "数据中心形象",
    "Decrease Research time by 10": "研究时间减少 10",
    "Decrease Research time by 20": "将研究时间减少 20",
    "Decrease Research time by 30": "研究时间减少 30",
    "Decrease the refresh delay of the exchange rate": "减少汇率的刷新延迟",
    "Design & Gimmicks": "设计与噱头",
    "Developed by Konrad Zuse! You couldn't start any better.": "由康拉德·祖泽开发！你再好不过了。",
    "Disable animations (for slow computers": "禁用动画（对于慢速计算机",
    "A: Go to tab \"Researches\". You should see the Research Center. Pay for unlocking! The Research Center will unlock many further upgrades. \n                        They will improve your BTC/s, your money for selling, more room for your rigs, and so on. It takes time to research them, but you can save time by paying money again.": "答：转到选项卡“研究”。 你应该看到研究中心。 付费解锁！ 研究中心将解锁许多进一步的升级。 \n 他们会提高你的 BTC/s、你的销售资金、更多的钻机空间等等。 研究它们需要时间，但您可以通过再次付费来节省时间。",
    "10^(TimeSinceResearch/8000) * BTC": "10^(自研究以来的时间/8000) * 比特币",
    "A: If you restart your game the first time, prestige mode is activated (Don't forget to export). For the next start you'll get coins; the amount of them is based on the money you made in this session.\n                        You will also get less coins for every Prestige Level you already got. It's harder to get 100 coins in Prestige 9 than in Prestige 1.": "A：如果您第一次重新启动游戏，则会激活声望模式（不要忘记导出）。 下一次开始，您将获得硬币； 它们的数量取决于您在此会话中赚到的钱。\n您也将获得更少的金币，因为您已经获得了每个声望等级。 在 Prestige 9 中获得 100 个硬币比在 声望 1 中更难。",
    "A: Bronze (25 rigs), Silver (50 rigs), Gold (100 rigs), Ruby (200 rigs), Emerald (500 rigs) and Diamond (1000 rigs": "A：青铜（25 个钻机）、银（50 个钻机）、金（100 个钻机）、红宝石（200 个钻机）、翡翠（500 个钻机）和钻石（1000 个钻机）",
    "A: Bronze (25 rigs), Silver (50 rigs), Gold (100 rigs), Ruby (200 rigs), Emerald (500 rigs) and Diamond (1000 rigs)": "A：青铜（25 个钻机）、白银（50 个钻机）、金（100 个钻机）、红宝石（200 个钻机）、翡翠（500 个钻机）和钻石（1000 个钻机）",
    "A: Click the big \"Hack some dollars\" Button for instant $1. You can also sell your Bitcoins (BTC).": "答：点击大“破解一些美元”按钮即刻获得 1 美元。您还可以出售您的比特币 (BTC)。",
    "A: Compare your besttimes with your friends using bad points. They are based on your Prestige Level and time needed. (Less points are better": "A：用坏点与朋友比较你的最佳时间。它们基于您的声望等级和所需时间。 （分数越少越好",
    "A: Compare your besttimes with your friends using bad points. They are based on your Prestige Level and time needed. (Less points are better)": "A：用坏点与朋友比较你的最佳时间。它们基于您的声望等级和所需时间。 （分数越少越好）",
    "A: Don't forget that you're playing in an beta version. If you find bugs, don't keep them! Email me or use the \"feedback\" option. Thank you": "A：别忘了你玩的是测试版。如果您发现错误，请不要保留它们！给我发电子邮件或使用“反馈”选项。谢谢",
    "A: First one will change your overall BTC/s. Second one will increase the base BTC/s value of machines.": "答：第一个会改变你的整体 BTC/s。第二个将增加机器的基本 BTC/s 值。",
    "A: First one will change your overall BTC/s. Second one will increase the base BTC/s value of machines. ": "答：第一个会改变你的整体 BTC/s。第二个将增加机器的基本 BTC/s 值。",
    "A: I won't, because hosting this game is no free (Doritos neither).": "A：我不会，因为托管这个游戏不是免费的（Doritos 也不是）。",
    "A: If your restart bonus (see in Settings -> Prestige Mode) is equal to 75 coins (or even bigger), you will level up your prestige.": "A：如果你的重启奖励（见设置 -> 声望模式）等于 75 个硬币（甚至更大），你将提升你的声望。",
    "A: It depends on the amount of Vodoo Cards you have. Funny, I know": "答：这取决于您拥有的 Vodoo 卡的数量。有趣，我知道",
    "A: It gets unlocked if you buy your first ASIC Miner. BETA Status, don't expect too much!": "答：如果您购买了您的第一个 ASIC 矿机，它就会解锁。 BETA 状态，不要期望太高！",
    "A: It gets unlocked if you buy your first ASIC Miner. BETA Status, don't expect too much! ": "答：如果您购买了您的第一个 ASIC 矿机，它就会解锁。 BETA 状态，不要期望太高！",
    "A: It's the current exchange rate for Bitcoin - US Dollar oriented to the realtime rate. Sell your BTC at a higher change to get even more money!  ": "答：这是针对实时汇率的比特币 - 美元的当前汇率。以更高的价格出售您的 BTC 以获得更多的钱！",
    "A: Just type": "答：只需输入",
    "Doge: D71HW5JAUH8sWgQEENFyd1vZQGNbX2j37F": "总督：D71HW5JAUH8sWgQEENFyd1vZQGNbX2j37F",
    "Don't forget eating!": "别忘了吃！",
    "double click - wipe entire savegame, restart from zero -": "双击 - 擦除整个存档，从零重新开始 -",
    "double click) Loads backup as main savegame and puts old main savegame as backup in storage.": "双击）将备份加载为主存档，并将旧的主存档作为备份存储。",
    "Double Size": "双倍尺寸",
    "Double your money instant": "让你的钱瞬间翻倍",
    "Doubletime": "双倍时间",
    "Ducktales": "鸭的故事",
    "End of time": "时间结束",
    "Enemie(s) left for boss": "敌人留给老板",
    "Even though I see your point; I hate annyoing ads also. That's reason why I tried to position them user-friendly as good as possible.": "即使我明白你的意思；我也讨厌 annyoing 广告。这就是为什么我试图将它们定位为尽可能用户友好的原因。",
    "Everything else will be resetted.": "其他一切都将被重置。",
    "Exchange API": "交换 API",
    "FAQs": "常见问题",
    "Fast Forward": "快进",
    "Fast forward long battles (max 25 seconds in the first round": "快进长战斗（第一轮最多25秒",
    "Favicon": "网站图标",
    "Feedback and other questions": "反馈和其他问题",
    "Fight Enemies to encounter boss and beat the boss to get a reward. Level up stages to unlock more!": "与敌人战斗以遇到老板并击败老板以获得奖励。升级阶段以解锁更多！",
    "firework": "焰火",
    "hover to see what they do": "悬停看他们做什么",
    "infinity": "无穷",
    "(double click - wipe entire savegame, restart from zero -": "（双击 - 擦除整个存档，从零重新开始 -",
    "(double click) Loads backup as main savegame and puts old main savegame as backup in storage.": "（双击）加载备份作为主存档并将旧的主存档作为备份存储。",
    "(hover to see what they do)": "（悬停看它们可以做什么）",
    "% of base cost": "基本成本的百分比",
    "+ cool Paint skills": "+很酷的绘画技巧",
    ">> Game does autosave every 20 seconds.<<": ">> 游戏每 20 秒自动保存一次。<<",
    "|\n                    Your location": "|\n 你的位置",
    "I'm using RevenueHits for advertising, because Goodle AdSense blocked me. Here is an ref link for you": "我正在使用 RevenueHits 做广告，因为 Goodle AdSense 阻止了我。 这是给你的参考链接",
    "Made the phonehous bosses stronger": "让电话屋老板变得更强大",
    "Removed classic theme": "删除了经典主题",
    "Removed one ugly ad because of some jQuery problems": "由于一些 jQuery 问题，删除了一个丑陋的广告",
    "Showing the btc cost for every hardware item is not opt-in anymore": "不再选择显示每个硬件项目的 btc 成本",
    "Some bug fixes (autosell": "一些错误修复（自动销售",
    "Test on a new server. I hope you won't lose your savegames.": "在新服务器上测试。 我希望你不会丢失你的存档。",
    "There are now ugly ads! I will build an option where you can turn them off, if you are too annoyed. (I need some bucks to pay the domain": "现在有丑陋的广告！ 如果您太生气，我将建立一个选项，您可以在其中关闭它们。 （我需要一些钱来支付域名",
    "\n                        Note: It is possible to gain coins through game events, not only by prestige mode.": "n 注意：不仅通过声望模式，还可以通过游戏活动获得金币。",
    "\n                    BTC/s ": "\n 比特币/秒",
    "\n                 Export and Import your savegame (backups, transfer to another computer": "\n 导出和导入您的游戏存档（备份、传输到另一台计算机",
    "\n                General feedback, questions and comments?": "\n 一般反馈、问题和意见？",
    "\n                Just email me": "\n 给我发电子邮件",
    "\n                Sources": "\n 来源",
    "\n                Use WASD/arrow keys to move, any other key to pause, Enter to restart": "\n 使用 WASD/箭头键移动，任何其他键暂停，Enter 重新启动",
    " 10^(TimeSinceResearch/8000) * BTC": "10^(TimeSinceResearch/8000) * 比特币",
    " Better graphics and animations will come! (Really, someday..)\n": "更好的图形和动画将会出现！ （真的，总有一天..）\n",
    " BTC ": "比特币",
    " BTC/s ": "比特币/秒",
    " check out our": "看看我们的",
    " Disable animations (for slow computers": "禁用动画（对于慢速计算机",
    " Fight Enemies to encounter boss and beat the boss to get a reward. Level up stages to unlock more!": "与敌人战斗以遇到老板并击败老板以获得奖励。升级阶段以解锁更多！",
    " Machines owned": "拥有的机器",
    " Money ": "钱",
    " Please report bugs, feedback or hints as usual via chat or mail at": "请像往常一样通过聊天或邮件报告错误、反馈或提示",
    " USD/BTC ": "美元/比特币",
    " Your health is your current amount of BTC/10.": "您的健康是您当前的 BTC/10 数量。",
    "- Thank you.": "- 谢谢。",
    ", where x is your money made this game.": "，其中 x 是你在这个游戏中赚到的钱。",
    ", will come to game later": ", 稍后会来游戏",
    ", you can still reach it at": ", 你仍然可以在",
    "Asynchronous Functions": "异步函数",
    "Classy x86 CPU for people with 'special needs'. 233Mhz pure mining power.": "适合有“特殊需求”的人的经典 x86 CPU。 233Mhz纯挖矿算力。",
    "Dark Basement": "黑暗的地下室",
    "Further upgrades": "进一步升级",
    "Gain 1x of your BTC/s computing speed as money through clicking": "通过点击获得 1 倍的 BTC/s 计算速度作为金钱",
    "Invented by Research Center 1": "研究中心发明 1",
    "Maybe something will appear..": "也许会出现什么。。",
    "Mommy does not like the new place for your rigs...": "妈妈不喜欢你的钻机的新地方......",
    "Multiplies BTC/s by 10": "将 BTC/s 乘以 10",
    "Overclocking": "超频",
    "Pay 8,500$ to save 25% of remaining time": "支付 8,500 美元可节省 25% 的剩余时间",
    "PSU Efficiency 70+": "电源效率 70+",
    "Quality assurance": "质量保证",
    "Reduces machine costs by 1": "机器成本降低 1",
    "Research Center 2": "研究中心2",
    "RESEARCH READY!": "研究就绪！",
    "Some say, it passed the 1-Ghz mark!": "有人说，它通过了 1-Ghz 大关！",
    "Using Glide for graphic-accelerated mining power.": "使用 Glide 获得图形加速的挖矿能力。",
    "You researched successfully 'Research Center'": "您成功研究了“研究中心”",
    "Pay 10,000$ to save 25% of remaining time": "支付 10,000 美元可节省 25% 的剩余时间",
    "Your Mining Rig As A Botnet": "作为僵尸网络的矿机",
    "Boost your mining power with nothing else than Intel's high-tech server CPU!": "借助英特尔的高科技服务器 CPU 提升您的挖矿能力！",
    "Pay 15,000$ to save 25% of remaining time": "支付 15,000 美元可节省 25% 的剩余时间",
    "Clickbot [locked]  [+8": "点击机器人 [未解锁] [+8",
    "Clickception [locked]  [+2": "Clickception [未解锁] [+2",
    "Do 9 clicks per second": "每秒点击 9 次",
    "Don't click a single random for 24h (One click before required": "24小时内不要随意点击（需要先点击一下）",
    "Don't forget eating! [locked]  [+5": "别忘了吃！ [未解锁] [+5",
    "Ducktales [locked]  [+2": "鸭子故事 [未解锁] [+2",
    "End of time [locked]  [+10": "时间结束 [未解锁] [+10",
    "Export you savegame 30 times": "导出你的存档 30 次",
    "First bronze award": "首届铜奖",
    "First gold award": "首届金奖",
    "First ruby award": "第一个红宝石奖",
    "First silver award": "首届银奖",
    "Get 300 coins at once": "一次获得300金币",
    "Get help from Gyro Gearloose": "从 Gyro Gearloose 获得帮助",
    "Hacking Expert [locked]  [+15": "黑客专家 [未解锁] [+15",
    "Have every bronze award": "拥有每一个铜奖",
    "Have every ruby award": "获得所有红宝石奖",
    "Have every silver award": "拥有每一个银奖",
    "Hit 30 coins in TRON": "在 TRON 中击中 30 个硬币",
    "Holy Grail [locked]  [+100": "圣杯 [未解锁] [+100",
    "I think you can stop now [locked]  [+15": "我想你现在可以停下来了[未解锁][+15",
    "Inflation [locked]  [+5": "通货膨胀 [未解锁] [+5",
    "Just the beginning [locked]  [+1": "才刚刚开始[未解锁][+1",
    "Just the beginning v2 [locked]  [+2": "刚刚开始 v2 [未解锁] [+2",
    "Legacy [locked]  [+10": "遗产 [未解锁] [+10",
    "Make 1 million dollar without any hack attacks (in wallet) (prestige allowed": "在没有任何黑客攻击的情况下赚取 100 万美元（在钱包中）（允许声望",
    "mega.co.nz [locked]  [+5": "mega.co.nz [未解锁] [+5",
    "Meh [locked]  [+10": "嗯[未解锁] [+10",
    "No risk [locked]  [+2": "没有风险[未解锁] [+2",
    "One Mille [unlocked]  [1": "一英里 [已解锁] [1",
    "Open the command line": "打开命令行",
    "Patience [unlocked]  [30": "耐心 [已解锁] [30",
    "Prestige [locked]  [+50": "威望 [未解锁] [+50",
    "Reach Prestige 3": "达到声望 3",
    "reached after 12m, 2s": "12m，2s后到达",
    "reached after 26m, 2s": "26m，2s后到达",
    "reached after 3m, 22s": "3m, 22s 后到达",
    "Research 5 Upgrades": "研究 5 升级",
    "Reset NOW [locked]  [+30": "立即重置 [未解锁] [+30",
    "Save up 1,000$": "节省 1,000 美元",
    "Save up 66 trillion  Bitcoins": "节省 66 万亿比特币",
    "Sell Bitcoins worth 450 quadrillion $ at once!": "一次卖出价值 450 万亿美元的比特币！",
    "Spare your finger [locked]  [+30": "饶了你的手指[未解锁] [+30",
    "Status: Online [locked]  [+1": "状态：在线[未解锁] [+1",
    "Status: Reallife [unlocked]  [1": "状态：现实生活 [已解锁] [1",
    "Status: Sheldon [locked]  [+55": "状态：谢尔顿 [未解锁] [+55",
    "Stay straight online for 6 hours!": "连续在线6小时！",
    "Terminals ain't only for airplanes [locked]  [+1": "航站楼不仅适用于飞机 [未解锁] [+1",
    "That wouldn't be possible! [locked]  [+5": "那是不可能的！ [未解锁] [+5",
    "To the stars [locked]  [+15": "给星星[未解锁] [+15",
    "Unlock Jupiter (Adventure Mode": "解锁木星（冒险模式",
    "up to date [locked]  [+1": "最新的 [未解锁] [+1",
    "Well, that escalated quickly [locked]  [+1": "嗯，升级很快[未解锁] [+1",
    "Why not ten? [locked]  [+1": "为什么不是十个？ [未解锁] [+1",
    "x": "X",
    "You crazy [locked]  [+1": "你疯了[未解锁] [+1",
    "You tried to hack google.com": "你试图入侵 google.com",
    "300x Kim, I can't believe it, you did it!": "300x Kim，我不敢相信，你做到了！",
    "3dfx Vodoo Graphics '96": "3dfx 巫毒图形 '96",
    "BTC/s Botnet": "BTC/秒 僵尸网络",
    "BTC/s rate x2 for 15s (+Research Speed x10": "BTC/秒 速率 x2 持续 15s (+研究速度 x10",
    "Intel's 64-bit dual-core CPU. Unleash the beast.": "因特尔 的 64 位双核 CPU。 释放野兽。",
    "PSU Efficiency 80+": "PSU 效率 80+",
    "Reduces machine costs by additional 2%. Eco!": "将机器成本额外降低 2%。 Eco！",
    "Boost your mining power with nothing else than AMD's... decent CPU!": "提升你的挖矿能力美元什么比用 AMD 的 CPU……更体面！",
    "It's no waste of energy..really mom, trust me! I'm an engineer..": "这不是浪费能源..真的妈妈，相信我！ 我是个工程师..",
    "Be online for 200 seconds [+1": "在线 200 秒 [+1",
    "Buy a brandnew ZUSE Z3 [+1": "购买全新 ZUSE Z3 [+1",
    "Click 250 times [+2": "点击 250 次 [+2",
    "Hack your first dollar [+1": "破解你的第一美元 [+1",
    "No Researches available...": "没有可用的研究...",
    "'Clickception' unlocked": "“点击接收”已解锁",
    "'Is this even legal?' unlocked": "“这合法吗？” 解锁",
    "'New era' unlocked": "“新时代”解锁",
    "'Status: Reallife' unlocked": "“状态：现实生活”解锁",
    "Optimized for mining. 10 times.": "针对采矿进行了优化。 10次​​。",
    "'up to date' unlocked": "“最新”解锁",
    "Just the beginning [unlocked]  [1": "才刚刚开始[解锁][1",
    "Pay 240,000$ to save 25% of remaining time": "支付 240,000 美元可节省 25% 的剩余时间",
    "Research 5 Upgrades [+1": "研究 5 升级 [+1",
    "You researched successfully 'PSU Efficiency 70+'": "您成功研究了“PSU 效率 70+”",
    "'Just the beginning' unlocked": "“刚刚开始”解锁",
    "Bronze award assigned": "分配的铜奖",
    "First bronze award [+1": "首届铜奖 [+1",
    "Be online for 2 hours [+1": "Be online for 2 hours [+1",
    "serious sponsoring": "认真的赞助",
    "Invented by Research Center 2": "研究中心 2 发明",
    "Last research center upgrade": "最终研究中心升级",
    "Money On My Mind": "钱在我心里",
    "More space for your rigs. Daddy approves.": "为您的钻机提供更多空间。 爸爸同意了。",
    "Multiplies BTC/s by 50": "将 BTC/s 乘以 50",
    "Overclocking: Free Multi": "超频：免费多",
    "PSU Efficiency 95+": "电源效率 95+",
    "Reduces machine costs by additional 5": "将机器成本额外降低 5",
    "Research Center 3": "研究中心3",
    "'Well, that escalated quickly' unlocked": "“嗯，升级很快”解锁",
    "Calculate 100 BTC per second [+1": "每秒计算 100 BTC [+1",
    "Callback Functions": "回调函数",
    "Daddy's Garage": "爸爸的车库",
    "Double the money you get for hustling": "双倍的钱，你得到的喧嚣",
    "final release": "最终版本",
    "Increase your sell percentage to 110": "将您的销售百分比提高到 110",
    "Hustler": "好色之徒",
    "They gave you extra $251,450!": "他们给了你额外的 $251,450！",
    "Jon Doe donated you": "Jon Doe 捐赠了你",
    "You researched successfully 'Callback Functions'": "您成功研究了“回调函数”",
    "You researched successfully 'Daddy's Garage'": "您成功研究了“爸爸的车库”",
    "You researched successfully 'Money On My Mind'": "您成功研究了“我心中的钱”",
    "You should think about a new room, it's going to be confined in here..": "你应该考虑一个新房间，它会被限制在这里..",
    "You researched successfully 'Overclocking: Free Multi'": "您成功研究了“超频：免费多”",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Intel C4004 '70": "Intel C4004 '70",
    "Intel Core 2 Duo '06": "英特尔酷睿 2 双核 '06",
    "Intel Core 2 Duo Graphic": "英特尔酷睿 2 双核显卡",
    "Intel Pentium II '97": "英特尔奔腾 II '97",
    "Intel Pentium II Graphic": "英特尔奔腾 II 显卡",
    "Intel Xeon Nehalem '09": "英特尔至强 Nehalem '09",
    "Zuse Z3 '41": "Zuse Z3 '41",
    'Q: Where is the difference between BTC/s Multiplier and BTC/s base multiplier?': '问：BTC/s乘数和BTC/s基本乘数有何区别？',
    'Q: Why are there no serverwide stats?': '问：为什么没有服务器范围的统计信息？',
    'You don\'t have to calculate on your own, the game does it for you: Go to Settings -> Prestige Mode an see, how many coins you would get.': '您不必自己进行计算，游戏会为您完成：转到“设置”->“声望模式”，看看您将获得多少枚硬币。',
    'You get them trough': '你得到它们通过',
    'You\'ll get the difference between your old and new highscore as coins.': '你将以硬币的形式获得旧高分和新高分之间的差距。',
    'Q: Can I lose the upgrades from the shop?': '问：我可以从商店中丢失升级吗？',

    //原样
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "\t\t\t\t* ": "\t\t\t\t* ",
    "\t\t\t\t ": "\t\t\t\t ",
    "\t": "",
    "For every hack a certain counter will increase (maximum 500). On the way to 500 clicks, the money for every hack will be decreased. \n                        After a while of not hacking, the counter will automatically decrase. (It's not a bug, it's a feature": "对于每一次黑客攻击，都会增加一个计数器（最多 500 个）。 在达到 500 次点击的路上，每次 hack 的钱都会减少。 \n 一段时间不破解后，计数器会自动减少。 （这不是一个错误，这是一个功能",
    "| Prestige ": "| 声望 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "The amount of coins you will get is base on the money you made this game. (Earned coins don't influence prestige": "您将获得的硬币数量取决于您在此游戏中赚到的钱。 （赚取的金币不影响声望",
    "If you reset now, you would get": "如果你现在重置，你会得到",
    "Export and Import your savegame (backups, transfer to another computer": "导出和导入您的游戏存档（备份、传输到另一台计算机",
    "You'll keep achievements, coins and settings.": "您将保留成就、硬币和设置。",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^([\d\.]+)$/,
    /^x([\d\.]+)$/,
    /^\* (.+)$/,
    /^\(([\d\.,]+) \$\/฿$/,
    /^([\d\.,]+)\$\/฿$/,
    /^\(([\d\.,]+)\$\/฿$/,
    /^([\d\.]+)\:([\d\.]+)$/,
    /^([\d\.]+) million \$$/,
    /^([\d\.]+) million \$\/฿$/,
    /^\(([\d\.]+) million \$\/฿$/,
    /^([\d\.,]+) decillion$/,
    /^([\d\.,]+) million$/,
    /^([\d\.,]+) septillion$/,
    /^\$([\d\.,]+)$/,
    /^\$([\d\.]+) trillion$/,
    /^\$([\d\.]+) million$/,
    /^\$([\d\.]+) billion$/,
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^Lvl (\d+)$/, '等级 $1'],
    [/^machines are calculating (.+) Bitcoins per second$/, '机器每秒计算 $1 个比特币'],
    [/^Not reached yet (.+) made$/, '尚未达到 $1 已完成'],
    [/^Pay (.+) to save (.+) of remaining time$/, '支付 $1 可节省 $2 的剩余时间'],
    [/^(\d+)m$/, '$1分'],
    [/^reached after (\d+)m, (\d+)s$/, '$1分，$2秒 后达成'],
    [/^reached after (\d+)h, (\d+)m, (\d+)s$/, '$1小时，$2分，$3秒 后达成'],
    [/^(\d+) clicks$/, '$1 点击'],
    [/^(\d+) \(last (\d+)s ago$/, '$1 \($2秒 前'],
    [/^(\d+) \(last (\d+)m ago$/, '$1 \($2分钟 前'],
    [/^(\d+) \(last (\d+)m, (\d+)s ago$/, '$1 \($2分钟 $3秒 前'],
    [/^(\d+) \(last (\d+)h, (\d+)m, (\d+)s ago$/, '$1 \($2小时 $3分钟 $4秒 前'],
    [/^(\d+)m, (\d+)s$/, '$1分, $2秒'],
    [/^(\d+)h, (\d+)m$/, '$1小时，$2分'],
    [/^(\d+)h, (\d+)m, (\d+)s$/, '$1小时，$2分, $3秒'],
    [/^(\d+)m, (\d+)s left$/, '还需 $1分, $2秒'],
    [/^(\d+) Royal points$/, '$1 皇家点数'],
    [/^(\d+)\% complete$/, '已完成 $1\%'],
    [/^(\d+)s left$/, '还需 $1秒'],
    [/^(\d+)m left$/, '还需 $1分钟'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);